name: photoreg4
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - cmake=3.14.0
  - cudatoolkit=11.8
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - plyfile
  - tqdm
  - matplotlib
  - scipy
  - einops
  - trimesh
  - tensorboard
  - pyglet<2
  - open3d
  - pip
  - pip:
      - roma
      - opencv-python
      - e3nn
      - pytorch3d
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
